config/urls.py
from django.contrib import admin
from django.urls import include, path
from pybo import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('',views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name="question_modify"),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name="answer_modify"),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name="answer_delete"),

]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(null=True, blank=True)
    
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(null=True, blank=True)

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

pybo/forms.py
from django import forms
from pybo.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'content']
        # widgets = {
        #     'title' : forms.TextInput(attrs={'class':'form-control'}),
        #     'content' : forms.Textarea(attrs={'class':'form-control', 'rows':10})
        # }
        # labels = {
        #     'title' : '제목',
        #     'content' : '내용'
        # }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content':'답변내용',
        }

pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from pybo.models import Question, Answer
from pybo.forms import QuestionForm, AnswerForm
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.

def set_page_range(page_num):
    start_page = int(((int(page_num) - 1)//10)*10 + 1)
    end_page = int(((int(page_num) - 1)//10)*10 + 10)
    return start_page, end_page

def index(request):
    page_num = request.GET.get('page', '1') # check if param exists, and return 1 if not found /pybo
    question_list = Question.objects.order_by('-create_date')
    paginator = Paginator(question_list, 10)
    page = paginator.get_page(page_num) 

    start_page, end_page = set_page_range(page_num)
    context = {'question_list':page, 'start_page':start_page, 'end_page':end_page}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)

    context = {'question':question}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now()) # name = 'content'
    # answer = Answer(question=question, content=request.POST.get('content'), create_date=timezone.now())
    # answer.save()
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.author = request.user
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    return render(request, 'pybo/question_detail.html', {'question':question, 'form':form})

@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.author = request.user
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    
    return render(request, 'pybo/question_form.html', {'form':form})

@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request,'No permission')
        return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question) ##
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)
        
    else:
        form = QuestionForm(instance=question)
    context = {'form':form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, 'No permission')
        return redirect('pybo:deteil', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)

    context = {'answer':answer,'form':form}
    return render(request,'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, 'No permission')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}

<div class='container my-3'>
    <form method="post" class='post-form'>
        {% csrf_token %}
        {% include 'error.html' %}
        <div class="form-group">
            <label for='content'>content</label>
            <textarea class='form-control' name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:''}}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">save</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ question.author.username }}</div>
                    {% if question.modify_date %}
                    <div>{{ question.modify_date }}</div>
                    {% else %}
                    <div>{{ question.create_date }}</div>
                    {% endif %}
                    {% if request.user == question.author %}
                        <div class="my-3">
                            <a href="{% url 'pybo:question_modify' question.id %}"
                            class="btn btn-sm btn-outline-secondary">edit</a>
                            <a href="#" class="delete btn btn-sm btn-outline-secondary"
                            data-uri="{% url 'pybo:question_delete' question.id %}">delete</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    {% if answer.modify_date %}
                    <div>{{ answer.modify_date }}</div>
                    {% else %}
                    <div>{{ answer.create_date }}</div>
                    {% endif %}
                    {% if request.user == question.author %}
                        <div class="my-3">
                            <a href="{% url 'pybo:answer_modify' answer.id %}"
                            class="btn btn-sm btn-outline-secondary">edit</a>
                            <a href="#" class="delete btn btn-sm btn-outline-secondary"
                            data-uri="{% url 'pybo:answer_delete' answer.id %}">delete</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="POST">
        {% csrf_token %}
        {% include 'error.html' %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
            name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="POST" class="post-form my-3">
        {% csrf_token %}
        <!-- {{ form.as_p  }} -->
        {% include 'error.html' %}

        <div class="form-group">
            <label for="title">제목</label>
            <input type="text" class="form-control" name="title" id="title" value="{{ form.title.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장</button>
    </form> 
</div>
{% endblock%}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <table class="table">
        <thead class="thead-dark">
            <tr class="text-center thead-dark">
                <th>Num</th>
                <th style="width:50%">Title</th>
                <th>Writer</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %} 
            {% for question in question_list %}    
            <tr class="text-center">
                <td>{{ forloop.counter }}</td>
                <td class="text-left">
                    <a href="{% url 'pybo:detail' question.id %}">{{question.title}}
                    {% if question.answer_set.count %}
                        <span class='text-danger small ml-2'>{{ question.answer_set.count }}</span>
                    {% endif %}
                    </a>
                </td>
                <td>{{question.author.username}}</td>
                <td>{{question.create_date}}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan='3'>질문이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <ul class='pagination justify-content-center'>
        {% if question_list.has_previous %}
            <li class='page_item'>
                <a class='page-link' href='?page={{ question_list.previous_page_number }}'>Pre</a>
            </li>
        {% else %}
            <li class='page-item'>
                <a class='page-link' tabindex="-1" aria-disabled="true" href="#">Pre</a>
            </li>
        {% endif %}

        {% for page_num in question_list.paginator.page_range %}
            {% if page_num >= start_page and page_num <= end_page %}
                {% if page_num == question_list.number %}
                    <li class='page-item active' aria-current="page">
                        <a class='page-link' href='?page={{ page_num }}'>{{ page_num }}</a>
                    </li>
                {% else %}
                    <li class='page-item'>
                        <a class='page-link' href='?page={{ page_num }}'>{{ page_num }}</a>
                    </li>
                {% endif %}
            {% endif %}
        {% endfor %}

        {% if question_list.has_next %}
            <li class='page_item'>
                <a class='page-link' href='?page={{ question_list.next_page_number }}'>Next</a>
            </li>
        {% else %}
            <li class='page_item'>
                <a class='page-link' tabindex='-1' aria-disabled='true' href='#'>Next</a>
            </li>
        {% endif %}
    </ul>

    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문등록</a>
</div>

{% endblock %}