common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from pybo import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('',views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name="question_modify"),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name="answer_modify"),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name="answer_delete"),

]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label='email')

    class Meta:
        model = User
        fields = ('username', 'email')

common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import UserForm 

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<div class='container my-3'>
    <div class="row">
        <div class="col-4">
            <h4>Log in</h4>
        </div>
        <div class="col-8 text-right">
            <span>
                <a href="{% url 'common:signup' %}">Sign up</a>
            </span>
        </div>
    </div>
    <form method="POST" class='post-form' action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{next}}">
        {% include 'error.html'%}
        <div class='form-group'>
            <label for='username'>ID</label>
            <input type="text" class='form-control' name="username" id="username"
            value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">PW</label>
            <input type="password" class="form-control" name="password" id="password"
            value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">Log in</button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>Sign up</h4>
        </div>
        <div class="col-8 text-right">
            <span><a href="{% url 'common:login' %}">Log in</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "error.html" %}
        <div class="form-group">
            <label for="username">Name</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">Password</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">Password Check</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">create</button>
    </form>
</div>
{% endblock %}